[project]
name = "supply-chain-reviews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "bs4>=0.0.2",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.6",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "plotly>=6.6.0",
    "seaborn>=0.13.2",
    "spacy>=3.8.11",
    "textblob>=0.19.0",
    "textblob-fr>=0.2.0",
    "wordcloud>=1.9.6",
    "sentence-transformers[openvino]>=5.3.0",
    "openvino>=2026.0",   # force une version compatible
    "optimum-intel>=1.27.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pip>=26.0.1",
]

[tool.uv]
environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64' and python_version >= '3.12' and python_version < '3.15'",
]

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true
